### ISSUE TITLE
extend parent router meta data 

### ISSUE THREAD

**Issue by jackqiu0123** [hannoeru/vite-plugin-pages#285]
### Describe the bug

same as title
parent  page
`
<route lang="yaml">
name: listOrApply
meta:
    hide: true
    name: listOrApply
</route>
`

child page
`
<route lang="yaml">
name: listSymbol
meta:
    name: listSymbol
</route>
`

then i found route meta like this
`
hide: true
name: "listSymbol"
`

### Reproduction

null

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.44 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Chrome Canary: 107.0.5254.0
    Safari: 15.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jackqiu0123** [comment]
@hannoeru
