### ISSUE TITLE
[Question] - How to define title, meta, middlewares for React?

### ISSUE THREAD

**Issue by sujit-baniya** [hannoeru/vite-plugin-pages#357]
### Description

There's not much example for React.

I'm trying to use this plugin in react, everything works fine. But unable to define the page title, meta or middlewares like auth. Please suggest how could I do it?

### Suggested solution

Add extended examples for React

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hannoeru** [comment]
We only provide a way to generate routes from file structure, so please check router-router's documentation for more detials.
