### ISSUE TITLE
TSX/JSX consider support to define meta by jsdoc with import types

### ISSUE THREAD

**Issue by morlay** [hannoeru/vite-plugin-pages#394]
### Description

We could extract meta from Typescript jsdoc

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#import-types

Not like yaml, 
with Typescript jsdoc,
we could got strongly type for route meta.

### Suggested solution

```tsx
/**
 * @property {"account"} meta.name
 * @property {typeof import("@mdi/js").mdiPlus} meta.icon
 */
export default defineComponent({})  
```
Then we could pick the info from jsdoc.

To generate route with picked meta.

```
import { mdiPlus } from  "@mdi/js"

const component = {
  meta:  {
    name: "account", 
    icon: mdiPlus
  }
}

const routes = [{ component, ... }]
```

For import type, we could generate routes with required module imports.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
