### ISSUE TITLE
Add dynamic meta to dynamic routes

### ISSUE THREAD

**Issue by SelfhostedPro** [hannoeru/vite-plugin-pages#417]
### Description

If there's not already a way that's undocumented, it's not possible to set dynamic metadata on dynamic routes. It would be really nice to be able to add this info so that it can easily be referenced.

### Suggested solution

If you have a route with params: `[name].vue` it would be great to be able to sub it in the route block. ie:
```vue
<route lang="yaml">
    meta:
        title: {{ name }}
        layout: default
</route>
```
or 
```vue
<route lang="yaml">
    meta:
        title: $name
        layout: default
</route>
```

### Additional context

`

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hannoeru** [comment]
Out of scope
